@startuml type_graph_class_diagram
title "Type Graph Class Diagram"


class Department <<abstract>> {
  name: string
}

class Sales
class Engineering 
class IT
class HR 


Sales --|> Department
Engineering -left-|> Department
IT --|> Department
HR -right-|> Department

class Organization {
  name: string
}

class User {
  name: string
}

class Device {
  deviceType: string
  os: string
  accepts_ntlm: boolean
}

class EmailAccount {
  role: string
  domain: string
  status: string
  compromised: boolean
}

class Server {
  name: string
  os: string
  accepts_ntlm: boolean
}

class Host {
  os: string
  compromised: boolean
  accepts_ntlm: boolean
}

class Service {
  type: string
  exposed: boolean
}

class File {
  name: string
  isSensitive: boolean
  writable: boolean
  tampered: boolean
}

class Credentials {
  owner: string
  reused: boolean
  compromised: boolean
}

class CredentialHash {
  owner: string
  stolen: boolean
}

Organization "1" -- "1..*" Department : has_department
Department "1..*" -- "0..*" User : employs
EmailAccount "0..*" -- "0..*" Device : uses
User "1" -- "1" EmailAccount : owns
EmailAccount "0..*" -- "0..*" EmailAccount : manages
Server "1" -- "1" Host : runs_on
Host "0..*" -- "0..*" Service : runs
EmailAccount "0..*" -- "0..*" File : can_write
EmailAccount "0..*" -- "0..*" File : can_read
User "1" -- "1..*" Credentials : has_credentials
User "0..*" -- "0..*" CredentialHash : has_hash
Host "0..*" -- "0..*" Host : can_access
EmailAccount "0..*" -- "0..*" Host : credentials_stored_on

@enduml