@startuml phishing
title "Phishing Attack Risk Rule"


rectangle "LHS : User has active email account" as LHS_BOX #line:gray {

  object "<b>User</b>" as user_lhs 
  object "<b>EmailAccount</b>" as EmailAccount_lhs  {
    status=active
  }
  object "<b>Message</b>" as phishingMessage_lhs #ccffcc {
    type="phishingMessage"
  }
  user_lhs -up-> EmailAccount_lhs : owns
  phishingMessage_lhs -.[#Green]left.-> EmailAccount_lhs : sent

}

rectangle "Outcome 1 : User clicked link and entered credentials" as OUTCOME_BOX_1 #line:gray {

    object "<b>User</b>" as user_r1 
  object "<b>EmailAccount</b>" as EmailAccount_r1  {
    compromised = true
    status=active
  }
  object "<b>Message</b>" as phishingMessage_r1 #ccffcc {
    type="phishingMessage"
  }
  user_r1 -up-> EmailAccount_r1 : owns
  phishingMessage_r1 -.[#Green]left.-> EmailAccount_r1 : sent

}

rectangle "Outcome 2 : User clicked link but did not enter credentials" as OUTCOME_BOX_2 #line:gray {

  object "user" as user2 #dddddd
  object "victimEmail" as victimEmail2 #dddddd {
    compromised = false
    status = active 
  }

 object "<b>Message</b>" as phishingMessage_r2 #ccffcc {
    type="phishingMessage"
  }
  object "securityAlert" as securityAlert2 #ccffcc {
    type = phishing_attempt
  }

  phishingMessage_r2 -.[#Green]left.-> victimEmail2 : sent
  user2 -up-> victimEmail2 : owns
  securityAlert2 .[#Green]down.> victimEmail2 : alerts 
}

rectangle "Outcome 3 : User ignored the email" as OUTCOME_BOX_3 #line:gray {

  object "user" as user3 #dddddd
  object "victimEmail" as victimEmail3 #dddddd {
    compromised = false
    status = active
  }
  
  object "<b>Message</b>" as phishingMessage_r3 #ccffcc {
    type="phishingMessage"
  }
  phishingMessage_r3 -.[#Green]left.-> victimEmail3 : sent
  user3 -up-> victimEmail3 : owns
}

rectangle "Outcome 4 : User reported the phishing attempt to sysadmin" as OUTCOME_BOX_4 #line:gray {

  object "user" as user4 #dddddd
  object "victimEmail" as victimEmail4 #dddddd {
    compromised = false
    status = active
  }
 
  object "securityAlert" as securityAlert4 #ccffcc {
   type = phishing_attempt
  }

  object "<b>Message</b>" as phishingMessage_r4 #ccffcc {
    type="phishingMessage"
  }
  phishingMessage_r4 -.[#Green]left.-> victimEmail4 : sent
  user4 -up-> victimEmail4 : owns
  victimEmail4 .[#Green]up.> securityAlert4 : reports

}
@enduml