@startuml
title "Phishing Attack Risk Rule"


rectangle "LHS : User has active email account" as LHS_BOX #line:gray {

  object "<b>User</b>" as user_lhs 
  object "<b>EmailAccount</b>" as EmailAccount_lhs  {
    status=active
  }
  object "<b>Message</b>" as phishingMessage_lhs #ccffcc {
    type="phishingMessage"
  }
  user_lhs -up-> EmailAccount_lhs : owns
  phishingMessage_lhs -.[#Green]left.-> EmailAccount_lhs : sent

}

rectangle "Type graph : Phishing Attack" as START_GRAPH_BOX #line:gray {

  object "<b>User</b>" as user_type 
  object "<b>EmailAccount</b>" as EmailAccount_type {
    bool:status
  }
  object "<b>Message</b>" as phishingMessage_type  {
    string:type
  }

  object "<b>SecurityAlert</b>" as securityAlert_type {
    string:type
  }

  object "<b>Attacker</b>" as attacker_type {

  } 

  user_type -up-> EmailAccount_type : owns
  phishingMessage_type -.left.-> EmailAccount_type : sent
  attacker_type -.right.-> EmailAccount_type : targets
  securityAlert_type .down.> EmailAccount_type : alerts

}

rectangle "Outcome 1 : User clicked link and entered credentials" as OUTCOME_BOX_1 #line:gray {

    object "<b>User</b>" as user_r1 
  object "<b>EmailAccount</b>" as EmailAccount_r1  {
    status=active
  }
  object "<b>Message</b>" as phishingMessage_r1 #ccffcc {
    type="phishingMessage"
  }
  user_r1 -up-> EmailAccount_r1 : owns
  phishingMessage_r1 -.[#Green]left.-> EmailAccount_r1 : sent
  note right of victimEmail1
    probability = 0.1
    cost = 30000 USD
  end note

}

rectangle "Outcome 2 : User clicked link but did not enter credentials" as OUTCOME_BOX_2 #line:gray {

  object "user" as user2 #dddddd
  object "victimEmail" as victimEmail2 #dddddd {
    compromised = false
    status = active 
  }

  object "securityAlert" as securityAlert2 #ccffcc {
    type = phishing_attempt
  }

 
  user2 -up-> victimEmail2 : owns
  securityAlert2 .[#Green]down.> victimEmail2 : alerts 
  note left of victimEmail2
    probability = 0.2
    cost = 5000 USD
  end note

}

rectangle "Outcome 3 : User ignored the email" as OUTCOME_BOX_3 #line:gray {

  object "user" as user3 #dddddd
  object "victimEmail" as victimEmail3 #dddddd {
    compromised = false
    status = active
  }
 
  user3 -up-> victimEmail3 : owns
  note left of victimEmail3
    probability = 0.6
    cost = 0 USD
  end note

}

rectangle "Outcome 4 : User reported the phishing attempt to sysadmin" as OUTCOME_BOX_4 #line:gray {

  object "user" as user4 #dddddd
  object "victimEmail" as victimEmail4 #dddddd {
    compromised = false
    status = active
  }
  object "phishingMessage" as phishingMessage4 #7a9df4
  object "securityAlert" as securityAlert4 #ccffcc {
   type = phishing_attempt
  }

  user4 -up-> victimEmail4 : owns
  phishingMessage4 -.[#7a9df4]left.-> victimEmail4 : targets
  victimEmail4 .[#Green]down.> securityAlert4 : reports
  note left of victimEmail4
    probability = 0.6
    cost = 0 USD
  end note

}
@enduml