@startuml credential_dumping
title "Credential Dumping from Compromised Host"

top to bottom direction

rectangle "LHS : Host must be compromised and admin credentials cached or stored locally " as LHS_BOX #line:gray {

  object "victimEmail" as EmailAccount_lhs <<EmailAccount>> #dddddd{
    compromised = false
  }
  object "host" as host_lhs  <<Host>> {
    compromised = true
  }

  object "user" as user_lhs <<User>> #dddddd {
  }
  user_lhs -up-> EmailAccount_lhs : owns
  EmailAccount_lhs -up-> host_lhs : credentials_stored_on
  
}

rectangle "Outcome 1 : Attacker successfully dumped admin credentials" as OUTCOME_BOX_1 #line:gray {

  object "victimEmail" as EmailAccount1 <<EmailAccount>> #dddddd{
    compromised = true
  }
  object "host" as host1  <<Host>> {
    compromised = true
  }
    object "user" as user_1 <<User>> #dddddd {
  }
  user_1 -up-> EmailAccount1 : owns
  EmailAccount1 -up-> host1 : credentials_stored_on

}

rectangle "Outcome 2 : Partial credentials were obtained and triggered the alert" as OUTCOME_BOX_2 #line:gray {
  
  object "victimEmail" as EmailAccount2 <<EmailAccount>> #dddddd{
    compromised = false 
  }
  object "host" as host2  <<Host>> {
    compromised = true
  }

  object "securityAlert" as securityAlert2 <<SecurityAlert>> #ccffcc {
    type = "credentials_used"
  }

    object "user" as user_2 <<User>> #dddddd {
  }
  user_2 -up-> EmailAccount2 : owns
  object "attacker" as attacker2 <<Attacker>> #ccffcc
  EmailAccount2 -up-> host2 : credentials_stored_on
  securityAlert2 -.[#green]left.-> EmailAccount2 : alerts
  attacker2 .[#green]down.> host2 : attacks

}

rectangle "Outcome 3 : Credential dumping attempt failed silently" as OUTCOME_BOX_3 #line:gray {

  object "victimEmail" as EmailAccount3 <<EmailAccount>> #dddddd{
    compromised = false
  }
  object "host" as host3  <<Host>> {
    compromised = true
  }
  object "user" as user_3 <<User>> #dddddd {
  }
  user_3 -up-> EmailAccount3 : owns
  EmailAccount3 -up-> host3 : credentials_stored_on

}

rectangle "Outcome 4 : Endpoint security detected the attempt" as OUTCOME_BOX_4 #line:gray {

  object "victimEmail" as EmailAccount4 <<EmailAccount>> #dddddd{
    compromised = false
  }
  object "host" as host4  <<Host>> {
    compromised = true
  }
  object "securityAlert" as securityAlert4 <<SecurityAlert>> #ccffcc {
    type = "credential_dumping"
  }
  EmailAccount4 -up-> host4 : credentials_stored_on

  object "attacker" as attacker4 <<Attacker>> #ccffcc{
  }
    object "user" as user_4 <<User>> #dddddd {
  }
  user_4 -up-> EmailAccount4 : owns
  attacker4 .[#green]down.> host4 : targets
  securityAlert4 -.[#green]left.-> EmailAccount4 : alerts

}
@enduml