@startuml credential_dumping
title "Credential Dumping from Compromised Host"

top to bottom direction

rectangle "LHS : Host must be compromised and admin credentials cached or stored locally " as LHS_BOX #line:gray {

  object "user" as user_lhs <<User>> #dddddd{
    role = admin
    credentials = secured
  }
  object "host" as host_lhs  <<Host>> {
    compromised = true
  }

  user_lhs -up-> host_lhs : credentials_stored_on
  
}

rectangle "Outcome 1 : Attacker successfully dumped admin credentials" as OUTCOME_BOX_1 #line:gray {

  object "user" as user1 <<User>> #dddddd{
    role = admin
    credentials = exposed
  }
  object "host" as host1  <<Host>> {

    compromised = true
  }

  user1 -up-> host1 : credentials_stored_on
  note left of host1
    probability = 0.25
    cost = 40000 USD
  end note

}

rectangle "Outcome 2 : Partial credentials were obtained" as OUTCOME_BOX_2 #line:gray {
  
  object "user" as user2 <<User>> #dddddd{
    role = admin
    credentials = critical 
  }
  object "host" as host2  <<Host>> {
    compromised = true
  }

  object "securityAlert" as securityAlert2 <<SecurityAlert>> #ccffcc {
    type = "credential_dumping"
  }
  object "attacker" as attacker2 <<Attacker>> #ccffcc
  user2 -up-> host2 : credentials_stored_on
  securityAlert2 -.[#green]left.-> host2 : alerts
  attacker2 .[#green]down.> host2 : targets
  note left of host2
    probability = 0.15
    cost = 15000 USD
  end note

}

rectangle "Outcome 3 : Credential dumping attempt failed silently" as OUTCOME_BOX_3 #line:gray {

  object "user" as user3 <<User>> #dddddd{
    role = admin
    credentials = secured
  }
  object "host" as host3  <<Host>> {
    compromised = true
  }

  user3 -up-> host3 : credentials_stored_on


  note left of host3
    probability = 0.5
    cost = 0 USD
  end note

}

rectangle "Outcome 4 : Endpoint security detected the attempt" as OUTCOME_BOX_4 #line:gray {

  object "user" as user4 <<User>> #dddddd{
    role = admin
    credentials = secured
  }
  object "host" as host4  <<Host>> {
    compromised = true
  }
  object "securityAlert" as securityAlert4 <<SecurityAlert>> #ccffcc {
    type = "credential_dumping"
  }
  user4 -up-> host4 : credentials_stored_on

  object "attacker" as attacker4 <<Attacker>> #ccffcc{
  }
  attacker4 .[#green]down.> host4 : targets
  securityAlert4 -.[#green]left.-> host4 : alerts
  note left of host4
    probability = 0.1
    cost = 5000 USD
  end note

}
@enduml